<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Employee Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; line-height: 1.4; color: #333; }
        .container { padding: 15px 20px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #f97316; padding-bottom: 15px; }
        .company-name { font-size: 18px; font-weight: bold; color: #f97316; }
        .report-title { font-size: 14px; font-weight: bold; margin-top: 5px; }
        .report-period { font-size: 11px; color: #666; margin-top: 3px; }
        .summary-table { width: 100%; margin-bottom: 20px; border-collapse: collapse; }
        .summary-table td { padding: 8px 12px; font-size: 11px; }
        .summary-table .label { font-weight: bold; color: #555; }
        .summary-table .value { font-weight: bold; font-size: 13px; }
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; font-size: 9px; }
        .data-table th { background-color: #f97316; color: white; padding: 6px 5px; text-align: left; font-weight: bold; }
        .data-table td { padding: 5px; border-bottom: 1px solid #e5e5e5; }
        .data-table tr:nth-child(even) { background-color: #fafafa; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .footer { margin-top: 20px; text-align: center; color: #888; font-size: 9px; border-top: 1px solid #e5e5e5; padding-top: 10px; }
        .status-active { color: #166534; font-weight: bold; }
        .status-inactive { color: #991b1b; font-weight: bold; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="company-name"><?php echo e($company->name ?? 'ArthaVidhi'); ?></div>
            <div class="report-title">Employee Report</div>
            <div class="report-period">Month: <?php echo e($month->format('F Y')); ?></div>
        </div>

        <table class="summary-table">
            <tr>
                <td class="label">Total Employees:</td>
                <td class="value"><?php echo e($summary['total_employees']); ?></td>
                <td class="label">Active:</td>
                <td class="value"><?php echo e($summary['active_employees']); ?></td>
                <td class="label">Monthly Salary:</td>
                <td class="value">Rs. <?php echo e(number_format($summary['total_monthly_salary'], 0)); ?></td>
            </tr>
        </table>

        <table class="data-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Department</th>
                    <th>Position</th>
                    <th class="text-right">Salary</th>
                    <th class="text-center">Status</th>
                    <th>Join Date</th>
                    <th>Phone</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                <?php $__currentLoopData = $employees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $employee): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <tr>
                    <td><?php echo e($index + 1); ?></td>
                    <td><?php echo e($employee->name); ?></td>
                    <td><?php echo e($employee->departmentModel->name ?? 'N/A'); ?></td>
                    <td><?php echo e($employee->position ?? $employee->designation ?? 'N/A'); ?></td>
                    <td class="text-right">Rs. <?php echo e(number_format($employee->salary, 0)); ?></td>
                    <td class="text-center">
                        <?php if($employee->is_active): ?>
                        <span class="status-active">Active</span>
                        <?php else: ?>
                        <span class="status-inactive">Inactive</span>
                        <?php endif; ?>
                    </td>
                    <td><?php echo e($employee->joining_date ? $employee->joining_date->format('d M, Y') : ($employee->hire_date ? $employee->hire_date->format('d M, Y') : 'N/A')); ?></td>
                    <td><?php echo e($employee->phone ?? 'N/A'); ?></td>
                    <td><?php echo e($employee->email); ?></td>
                </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            </tbody>
        </table>

        <div class="footer">
            <p>Generated by ArthaVidhi Billing System on <?php echo e(now()->format('d M, Y')); ?></p>
        </div>
    </div>
</body>
</html>
<?php /**PATH D:\billing\resources\views\pdf\employee-report.blade.php ENDPATH**/ ?>